name: GitHubActions-Demo
'on':
  push:
    branches:
      - main
jobs:
  build_release:
    runs-on: ubuntu-latest
    name: build_release
    steps:
      - uses: actions/checkout@v2
      - name: Checkout
        with:
          node-version: 14.x
          java-version: '1.8'
          distribution: 'adopt'
        uses: actions/setup-node@v2
      - name: Nessq
        run: |
          git clone https://github.com/rahulkarri/react-shopping-cart-nessq.git react-shopping-cart-nessq
          cd react-shopping-cart-nessq
          mvn --version
          
       
