name: github-action
'on':
  push:
    branches:
      - main
jobs:
  build_release:
    runs-on: ubuntu-latest
    name: build_release
    steps:
      - uses: actions/checkout@v2
      - name: Checkout
        with:
          node-version: 14.x
        uses: actions/setup-node@v2
      - name: SonarQube
        env:
          SONAR_URL: https://sonarqube.ness-ie-practice.com
          SONAR_PROJECT_KEY: vegetable-shopping-cart
          SONAR_TOKEN: afa3388a02a9966c446ba10461ee2ef5aa5eca40
        with:
          args: >-
            -Dsonar.projectKey=${{ env.SONAR_PROJECT_KEY  }} -Dsonar.sources=.
            -Dsonar.css.node=. -Dsonar.host.url=${{ env.SONAR_URL  }}
            -Dsonar.login=${{ env.SONAR_TOKEN  }}
      - name: Package
        run: |
          npm install && REACT_APP_ENVIRONMENT=production npm run build
