name: test-githubactions
'on':
  push:
    branches:
      - main
jobs:
  build_release:
    runs-on: ubuntu-latest
    name: build_release
    steps:
      - uses: actions/checkout@v2
      - name: Checkout
        with:
          node-version: 14.x
        uses: actions/setup-node@v2
      - name: NessQ
        run: >-
          git clone -b main
          https://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@github.com/rahulkarri/react-shopping-cart-nessq
          react-shopping-cart-nessq
                      cd react-shopping-cart-nessq
                      wget https://archive.apache.org/dist/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.tar.gz
                      tar xzvf apache-maven-3.6.3-bin.tar.gz
                      export PATH=apache-maven-3.6.3/bin:$PATH
                      mvn clean test -Drp.enable=true -Drp.launch=IE-Practice-Workflow
