name: test-githubactions
'on':
  push:
    branches:
      - main
jobs:
  build_release:
    runs-on: ubuntu-latest
    name: build_release
    steps:
      - uses: actions/checkout@v2
      - name: Checkout
        with:
          node-version: 14.x
        uses: actions/setup-node@v2
      - name: NessQ
        uses: actions/checkout@v2
        with:
          repository: rahulkarri/react-shopping-cart-nessq
          token: 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
