name: veg-shopping-cart
on:
  push:
    branches:
      - 'main'
  pull_request: {}
jobs:
  build_test_release:
    runs-on: ubuntu-latest
    name: Setup
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Checkout
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: |-
          npm cache clean --force
          npm install && CI=false REACT_APP_ENVIRONMENT=production npm run build
